urllib3/sync_connection.py
If this is synchronous, we would need to instead switch the return to:
`return await (self._start_http_request(request, self._state_machine, self._sock))`
to avoid a SyntaxError
=> Change SyncHTTP1Connection.send_request to async

trio_test.py, urllib3/backends/_util.py, urllib3/backends/sync_backend.py, urllib3/backends/trio_backend.py, urllib3/backends/twisted_backend.py, urllib3/connectionpool.py, urllib3/poolmanager.py, urllib3/response.py, urllib3/sync_connection.py
I gave a try at the mechanical parts of njsmith/urllib3#1, ie. passing the backend from the pools to the connection, adding async/await keywords, and fixing minor issue in the trio backend.
Running `python3 test_trio.py` prints:
```
Response(status_code=200, headers=[(b'connection', b'keep-alive'), (b'server', b'meinheld/0.6.1'), (b'date', b'Tue, 02 Jan 2018 02:12:45 GMT'), (b'content-type', b'text/plain'), (b'content-length', b'30'), (b'access-control-allow-origin', b'*'), (b'access-control-allow-credentials', b'true'), (b'x-powered-by', b'Flask'), (b'x-processed-time', b'0.00075101852417'), (b'via', b'1.1 vegur')], http_version=b'1.1', reason=b'OK')
200
b''
```
So we see the headers of the h11 response in the trio backend but I don't know how to expose that in the urllib3 Response …
=> Send request through trio backend

setup.py
This fixes `python setup.py build` and `python setup.py bdist_wheel`.
The bleaching script was slightly improved to detect the encoding and handle backslashes (here is the [previous version](https://gist.github.com/pquentin/188f139be4c1bd5731b54bb2f7c29e41)). When run on the CPython 3.4 standard library, the only differences are whitespace changes: it turns @njsmith was right, we can't reconstruct the file exactly by only using the tokens, even if the resulting AST is the same. This will need to be fixed at some point, but it's not urgent since the fixes won't make any difference on urllib3.
I ended up including the bleaching script inside the setup.py file to avoid headaches. I think the end state is putting the script in its own package and using it as a PEP 518 build dependency. …
=> Integrate bleaching in setup.py

dev-requirements.txt, test/contrib/test_pyopenssl.py, test/contrib/test_socks.py, test/test_connection.py, test/test_connectionpool.py, test/test_no_ssl.py, test/test_poolmanager.py, test/test_sync_connection.py, test/with_dummyserver/test_chunked_transfer.py, test/with_dummyserver/test_connectionpool.py, test/with_dummyserver/test_https.py, test/with_dummyserver/test_poolmanager.py, test/with_dummyserver/test_proxy_poolmanager.py, test/with_dummyserver/test_socketlevel.py, urllib3/_async/connection.py, urllib3/_async/connectionpool.py, urllib3/_async/poolmanager.py, urllib3/_backends/sync_backend.py, urllib3/contrib/socks.py
Too much tests are skipped, and nose/unittest/unittest2 are still used, and travis integration is not set up yet, but no tests fail when using pytest.
=> Ensure no failure with pytest

test/contrib/test_pyopenssl.py, test/contrib/test_socks.py, test/with_dummyserver/test_chunked_transfer.py, test/with_dummyserver/test_connectionpool.py, test/with_dummyserver/test_https.py
We want to minimize the number of skipped tests, and maximize successful (!) and xfailed tests.
The exception is the `pytestmark` in `test/contrib/test_securetransport.py`: it did not change anything: all affected tests do timeout.
=> Skip at test level

setup.cfg, test/test_response.py, test/with_dummyserver/test_https.py
I'm not too sure about the response fix, but on the other hand why should we close an object that has no close method?
=> Misc fixes

dev-requirements.txt, runtests.py, setup.cfg
The exception is tornado which is still pinned at 4.x.
Maybe we should use ~= to pin to major versions?
=> Bump requirements versions

runtests.py
But still return a non-zero integer on command errors, for CI.
So I scratch itch after itch on runtests.py, but maybe making tox work would not be that hard? I don't know.
=> runtests: Stop displaying unrelated stack traces

test/with_dummyserver/test_chunked_transfer.py
Apparently we fixed these at some point
=> Re-enable chunked transfer tests

tox.ini
This appears to allow me to run the tests without messing around with virtualenv's a la the `runtests.py` script.
=> move _sync codegen to tox.ini

demo/async-demo.py, test/test_backends.py, test/test_no_ssl.py, test/with_dummyserver/test_chunked_transfer.py, test/with_dummyserver/test_no_ssl.py, urllib3/_async/connection.py, urllib3/_backends/__init__.py, urllib3/_backends/_loader.py, urllib3/_backends/twisted_backend.py, urllib3/backends.py
This pull request is based on @oliland's PR and completes it:
* tests are now fixed
* the demo is fixed
* I've finally managed to understand [how the async test should work](https://github.com/python-trio/urllib3/pull/42#discussion_r186170793)
So the point of that test is simply to know whether we're running in async mode or bleached mode. We can only run in async mode with a Python that supports everything we need (3.6 right now), so the test is simple but has to be in a part of the code that is going to be bleached.
I decided to put this in _async/connection.py because it's the last place that accepts a backend, which means we can validate the backend in a single place. (Which also means that we did not really need to separate normalize_backend and load_backend.)
The history is getting …
=> Take two: Ensure `import urllib3` can succeed even if trio and twisted aren't installed

test/with_dummyserver/test_https.py
It was flaky in the master branch too, but that should have been fixed.
=> Restore test_client_no_intermediate

src/urllib3/_async/connection.py, src/urllib3/_async/connectionpool.py, src/urllib3/_backends/sync_backend.py, test/with_dummyserver/test_connectionpool.py, test/with_dummyserver/test_socketlevel.py
In urllib3 master, the read timeouts are set on the underlying socket. Then makefile() is called, and this is how the read timeout work. In the bleach-spike branche, I think we need to store the read timeout explicitly in the connection, because reading the response is done by iterating over the connection object.
=> Honor read timeouts

.travis.yml, MANIFEST.in, dev-requirements.txt, pyproject.toml, setup.py, test/contrib/test_securetransport.py, tox.ini
Thanks to the work of @RatanShreshtha and I, unasync is now available on PyPI: https://pypi.org/project/unasync/. This project switches urllib3 to use it.
`pip install -e .` works! 🎉 But tox does not. 😿 I need to find out what's the problem, since tox says PEP 518 is supported, and I followed its docs.
=> Try using unasync from PyPI

src/urllib3/_async/connectionpool.py, src/urllib3/_backends/sync_backend.py, test/with_dummyserver/test_https.py, test/with_dummyserver/test_proxy_poolmanager.py
We now accept server_hostname in HTTPSConnectionPool.
=> Fix test_server_hostname

src/urllib3/util/wait.py
We don't know yet if we'll progress fast enough to support Python 2, so
let's worry about this later.
=> Remove Python 2 only code from coverage reports

src/urllib3/_async/connection.py, test/with_dummyserver/test_socketlevel.py
I have added a check in for ipv6 host in `_build_tunnel_request` and accordingly modify the target, is there a better way ?
=> Fix test_connect_ipv6_addr.

test/with_dummyserver/test_socketlevel.py
Or at least they're less flaky than they used to be!
=> test_socketlevel: skip tests that are no longer flaky

CHANGES.rst, docs/user-guide.rst, src/urllib3/_async/connection.py, src/urllib3/_async/connectionpool.py, src/urllib3/util/ssl_.py, test/contrib/test_socks.py, test/test_connectionpool.py, test/test_util.py, test/with_dummyserver/test_https.py, test/with_dummyserver/test_no_ssl.py, test/with_dummyserver/test_proxy_poolmanager.py, test/with_dummyserver/test_socketlevel.py
This includes a Google App Engine tweak and a change to check SSL certificates by default. My understanding is that this was already the default since Cory Benfield's v2 branch, but this commit is more comprehensive, eg. it switches more tests to verified requests. I also tested locally that verification happens when just using urllib3 as a user.
And there are still flaky tests, but the US is sleeping, so the CI should be fast enough to avoid the flakiness.
=> Merge from master (January 25th, 2019)

.travis.yml, CHANGES.rst, LICENSE.txt, docs/requirements.txt, dummyserver/handlers.py, src/urllib3/contrib/socks.py, src/urllib3/fields.py, src/urllib3/util/ssl_.py, test/test_fields.py, test/test_ssl.py, tox.ini
This includes miscellaneous commits that don't touch the async parts, but it introduces https://github.com/urllib3/urllib3/pull/1566 which breaks on PyPy 2. I stared at the code to understand why this happens, and I just don't get it, so I marked this as xfail on PyPy 2 (which took me a lot of time!).
Oh, and we now use Travis "stages", so "allowed to fail" builds are no longer visually separated from normal builds.
What's left before catching up with the master branch:
* url parsing changes
* switch from tox to nox
* switch to black
* switch to pure pytest:
* assertions
* unittest removal
* replacing addCleanup with context managers
* TLS 1.3 post-handshake authentication
=> Merge from master (April 20th, 2019)

.travis.yml, CHANGES.rst, _travis/downstream/requests-requirements.txt, _travis/downstream/requests.sh, _travis/upload_coverage.sh, src/urllib3/_async/connectionpool.py, src/urllib3/_async/response.py, src/urllib3/packages/rfc3986/__init__.py, src/urllib3/packages/rfc3986/_mixin.py, src/urllib3/packages/rfc3986/abnf_regexp.py, src/urllib3/packages/rfc3986/api.py, src/urllib3/packages/rfc3986/exceptions.py, src/urllib3/packages/rfc3986/iri.py, src/urllib3/packages/rfc3986/misc.py, src/urllib3/packages/rfc3986/normalizers.py, src/urllib3/packages/rfc3986/uri.py, src/urllib3/packages/rfc3986/validators.py, src/urllib3/util/url.py, test/test_util.py, tox.ini
With this PR, we support Google's Brotli package and parse URLs with the rfc3986 package. There were only conflicts in response.py and connectionpool.py (and .travis.yml and tox.ini). As I can see the future, I can tell you that rfc3986 will be dropped in a later PR, so don't worry too much about it!
What's left before catching up with the master branch:
* switch from tox to nox
* switch to black
* switch to pure pytest:
* assertions
* unittest removal
* replacing addCleanup with context managers
* TLS 1.3 post-handshake authentication
=> Merge from master (April 24th, 2019, before Nox)

src/urllib3/_async/connectionpool.py, src/urllib3/_collections.py, test/test_collections.py
Fixes #109
> We're not using httplib (the old name for http.client), so
> all mentions of from_httplib can be removed from the code.
=> Remove HTTPHeaderDict.from_httplib

.github/FUNDING.yml, .travis.yml, CHANGES.rst, CONTRIBUTORS.txt, README.rst, dev-requirements.txt, docs/contributing.rst, src/urllib3/_async/connectionpool.py, src/urllib3/packages/rfc3986/__init__.py, src/urllib3/packages/rfc3986/misc.py, src/urllib3/util/ssl_.py, src/urllib3/util/url.py, test/test_ssl.py, test/test_util.py, test/with_dummyserver/test_socketlevel.py
So this places us just before the switch to black and to pure pytest.
The only interesting change here is "Load system CA certificates by default on empty HTTPSConnection". I made sure that the tests passed, but did not test anything locally.
codecov is still broken for Travis (HTTP 400 error) and AppVeyor (coverage report not found).
=> Merge from master (May 23th, 2019)

test/contrib/test_socks.py, test/with_dummyserver/test_chunked_transfer.py, test/with_dummyserver/test_connectionpool.py, test/with_dummyserver/test_https.py, test/with_dummyserver/test_no_ssl.py, test/with_dummyserver/test_poolmanager.py, test/with_dummyserver/test_proxy_poolmanager.py, test/with_dummyserver/test_socketlevel.py
This removes the addCleanup() calls. This is the only remaining big change, the next one is simply to drop unittest altogether.
=> Merge from master (June 6th, 2019)

CHANGES.rst, docs/user-guide.rst, test/test_response.py, test/test_ssl.py
I tried and fail to understand how we should adapt this commit to our work. Given that the current situation is likely to change (see #123), I did not merge the actual functionality, but only the test of the default behavior (and the CHANGES/docs as we're not currently touching those for easier merges).
=> Merge from master (July 26th, 2019)

src/urllib3/util/ssl_.py, test/test_ssl.py
Enable TLS 1.3 post-handshake authentication (#1635)
Fixes: https://github.com/urllib3/urllib3/issues/1634
Signed-off-by: Christian Heimes <christian@python.org>
* Add tests for TLS 1.3 PHA
Fixes: https://github.com/urllib3/urllib3/issues/1634
Signed-off-by: Christian Heimes <christian@python.org>
=> Merge from master (Aug 16th, 2019)

CHANGES.rst, README.rst, _travis/downstream/requests-requirements.txt, _travis/downstream/requests.sh, dev-requirements.txt, dummyserver/handlers.py, noxfile.py, src/urllib3/_async/connectionpool.py, src/urllib3/fields.py, src/urllib3/filepost.py, src/urllib3/util/ssl_.py, src/urllib3/util/url.py, test/__init__.py, test/appengine/conftest.py, test/contrib/test_securetransport.py, test/with_dummyserver/test_connectionpool.py, test/with_dummyserver/test_https.py
I realized that some upstream tests are using context manager where we don't use them, probably because we removed a few addCleanup calls manually at some point? I'll try to fix that after the current round of merges.
=> Merge from master (September 20th, 2019)

dev-requirements.txt, setup.cfg, src/urllib3/_async/connectionpool.py, src/urllib3/_async/poolmanager.py, test/conftest.py, test/with_dummyserver/async/test_poolmanager.py
Okay, now that we have removed unittest, the diff to get a trio test to work is much smaller.
Remaining problems:
* how do we avoid failing on Python 2 which can't even parse this file
* how do we skip the tests on Python 3.5 which is not currently supported as we use native async generators? With a `onlyPy3`-like decoration, the test is not even run
* how do we generate the sync test from the async ones and run against multiple backends?
I'm not planning to work on this until a few weeks, but ideas would be appreciated. cc @njsmith
=> First trio test

src/urllib3/_async/connectionpool.py, src/urllib3/_async/response.py, test/test_response.py, test/with_dummyserver/async/test_poolmanager.py
The idea here is just to make sure the existing way works, we don't refactor anything else.
We had to take the call to `read()` out of the constructor as we can't have await expressions there. This solution works since `HTTPConnectionPool.urlopen()` is the only place where responses are
instantiated. (App Engine does not count as we'll remove it later.)
=> Support async content preloading

setup.cfg, src/urllib3/_backends/_loader.py, test/async/test_backends.py, test/conftest.py, test/with_dummyserver/async/test_poolmanager.py
This will result in a better user experience, and also helps to reduce the differences between the sync and async tests, as you can see in  test/with_dummyserver/async/test_poolmanager.py.
=> Sniff async backends using sniffio

.github/workflows/ci.yml
Hopefully this will improve the coverage as codecov was not finding the coverage file on Windows so it simply was not uploaded.
=> Tell Windows codecov the file to upload

.github/workflows/ci.yml
Using the plan from @njsmith in #184:
> I guess we can just stick the codecov token in here in plaintext for now – I think the only danger is that someone could... maliciously upload false coverage reports? Seems like a pretty low risk to me. And then if Github/Codecov get their acts together and fix this, we can always revoke that token.
=> Fix GitHub Actions coverage for pull requests

README.rst
This is a first draft as requested by @njsmith in https://gitter.im/python-trio/hip?at=5e268f6269a7b51d4d54ecae.
You can look at the output here: https://github.com/pquentin/hip/tree/hip-readme
=> Document Hip in the README, not urllib3

dev-requirements.txt, test/with_dummyserver/async/test_poolmanager.py, test/with_dummyserver/conftest.py
The released version has a different configuration scheme for specifying backends.
=> Updated AnyIO test configuration

setup.py
To work around the GitHub bug from #205. The previous workaround did not work since GitHub noticed that the branch contained the same commits.
=> Fix compatibility with unasync 0.5.0

setup.cfg, src/hip/_backends/anyio_backend.py, src/hip/_backends/async_backend.py, src/hip/_backends/trio_backend.py
- Added `AsyncBackend` and `AsyncSocket` ABCs so we can maintain the same interface across all implementations. Will also be useful in the future for type hinting.
- Added `read_timeout` to `AsyncSocket.receive_some()` that currently does nothing so that `_read_until_event` is happy with all async socket interfaces.
- Use `suppress_ragged_eofs=True` and `server_hostname` parameters in `anyio.SocketStream.start_tls()`
- Potential fix for Trio TLS by calling `SSLStream.do_handshake()` within `TrioSocket.start_tls()` so that `getpeercert()` is available before sending data. Can revert this if we have a better idea in mind?
All of these changes combine so that the `async-demo.py` works with HTTPS! :)
=> Add AsyncBackend ABC, normalize backend interfaces

.readthedocs.yml, docs/_static/hackrtd.css, docs/_templates/fonts.html, docs/_templates/layout.html, docs/advanced-usage.rst, docs/conf.py, docs/contributing.rst, docs/index.rst, docs/requirements.txt
RTD is failing because it installs the project via `python setup.py install` before installing `dev-requirements.txt` so doesn't have `unasync`. Added a `readthedocs.yml` file so we can control the install order and have RTD use `pip install .` instead of `python setup.py install`
I also pulled most of Trio's template, it looks good for now and the docs now just need content to be improved to look really nice. No logo yet so that section is empty and didn't immediately link to the Trio Discourse. The Stackoverflow tag doesn't exist yet but doesn't hurt to link to nothing?
=> Use Trio RTD theme, add readthedocs.yml

setup.py, src/ahip/_backends/anyio_backend.py, src/ahip/connection.py, src/ahip/connectionpool.py, src/ahip/poolmanager.py, src/ahip/util/request.py, src/ahip/util/unasync.py, test/conftest.py, test/with_dummyserver/async/test_poolmanager.py, test/with_dummyserver/async_only/test_poolmanager.py, test/with_dummyserver/test_poolmanager.py
This PR adds support async files like `trio.wrap_file(open())` and `anyio.aopen()` and does some refactoring that will allow us to accept other async iterables as data sources easily.
- Made `set_file_position()` and `rewind_body()` able to handle async files
- Added an `unasync.py` file to `hip.util` for small unasync-related utilities like `anext()` and `await_if_coro()`. See https://github.com/python-trio/unasync/issues/65 for more info here too.
- Added `read_timeout` to `AnyIOSocket.receive_some()`, don't know how that bug wasn't caught earlier.
- Turned a lot of the internal request data stream functions into return async iterators. This blazes the trail for accepting async iterables in `body=`.
- Moved all tests related to file uploads into `test/with_dummyserver/async/`.
- Added …
=> Add support for async files as request body

src/ahip/__init__.py, src/ahip/connectionpool.py, src/ahip/filepost.py, src/ahip/util/__init__.py, src/ahip/util/ssl_.py, src/ahip/util/url.py, test/conftest.py, test/contrib/test_securetransport.py, test/test_filepost.py, test/test_util.py
- Removes `hip.util.url.get_host()`
- Removes `hip.util.url.split_first()`
- Removes behavior where `path=""` is set depending on whether `query` or `fragment` are set.
Now we always have `path=None` if `path=""`.
- Moved all `get_host()` test cases into `parse_url()` test suite
- Small lint fix (`l` and `r` -> `left` and `right`)
=> Remove deprecated urllib3 features

README.rst
I noticed that the 'async/await example' in `README` no longer worked after the changes discussed in #168 were made in #213.
The module rename should be straightforward. However I also found that the return value of `await r.read()` was `b''` ie. no longer included the data received in the first exchange, which was a bit concerning. I changed the example to just read the `data` property, which works at least for small responses.
Perhaps awaiting `read()` is still required - and it is a bug that the prior data is not included in the return value, but I am not sure enough to open that as an issue.
=> fixup async/await example after module rename #168 #213

src/ahip/base.py, test/test_connection.py
The generation of the `Host` header in `Request` relies on the interpreter's small integer cache.  The [comparison between the request port and the default port](https://github.com/python-trio/hip/blob/cab5c4aacda54ea04b02ff2957589c78f169b690/src/ahip/base.py#L70) should be using equality instead of identity checking.
=> Default port calculation relies on the small integer cache
